jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v13
        with:
          nix_path: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz"
